#需改為從txpull拿

puts 'Sport seeds importing...'


Sport.create(leader_spid: 1, name: "soccer", display_name: "足球", active: 1)
Sport.create(leader_spid: 2, name: "icehockey", display_name: "冰球", active: 1)
Sport.create(leader_spid: 3, name: "basketball", display_name: "籃球", active: 1)
Sport.create(leader_spid: 4, name: "rugby union", display_name: "橄欖球", active: 1)
Sport.create(leader_spid: 5, name: "tennis", display_name: "網球", active: 1)
Sport.create(leader_spid: 6, name: "us football", display_name: "美式足球", active: 1)
Sport.create(leader_spid: 7, name: "baseball", display_name: "棒球", active: 1)
Sport.create(leader_spid: 8, name: "handball", display_name: nil, active: 0)
Sport.create(leader_spid: 9, name: "pesapallo", display_name: nil, active: 0)
Sport.create(leader_spid: 10, name: "floorball", display_name: nil, active: 0)
Sport.create(leader_spid: 11, name: "bandy", display_name: nil, active: 0)
Sport.create(leader_spid: 12, name: "golf", display_name: nil, active: 0)
Sport.create(leader_spid: 13, name: "volleyball", display_name: "排球", active: 1)
Sport.create(leader_spid: 14, name: "cricket", display_name: nil, active: 0)
Sport.create(leader_spid: 15, name: "table tennis", display_name: nil, active: 0)
Sport.create(leader_spid: 16, name: "snooker", display_name: nil, active: 0)
Sport.create(leader_spid: 17, name: "futsal", display_name: nil, active: 0)
Sport.create(leader_spid: 18, name: "mixed martial arts", display_name: nil, active: 0)
Sport.create(leader_spid: 19, name: "boxing", display_name: nil, active: 0)
Sport.create(leader_spid: 20, name: "darts", display_name: nil, active: 0)
Sport.create(leader_spid: 21, name: "bowls", display_name: nil, active: 0)
Sport.create(leader_spid: 22, name: "motor sports", display_name: nil, active: 0)
Sport.create(leader_spid: 23, name: "gaelic football", display_name: nil, active: 0)
Sport.create(leader_spid: 24, name: "water polo", display_name: nil, active: 0)
Sport.create(leader_spid: 25, name: "cycling", display_name: nil, active: 0)
Sport.create(leader_spid: 26, name: "aussie rules", display_name: nil, active: 0)
Sport.create(leader_spid: 27, name: "hockey", display_name: nil, active: 0)
Sport.create(leader_spid: 29, name: "rugby league", display_name: nil, active: 0)
Sport.create(leader_spid: 30, name: "alpine skiing", display_name: nil, active: 0)
Sport.create(leader_spid: 31, name: "biathlon", display_name: nil, active: 0)
Sport.create(leader_spid: 32, name: "curling", display_name: nil, active: 0)
Sport.create(leader_spid: 33, name: "nordic combined", display_name: nil, active: 0)
Sport.create(leader_spid: 34, name: "ski jumping", display_name: nil, active: 0)
Sport.create(leader_spid: 35, name: "cross-country skiing", display_name: nil, active: 0)
Sport.create(leader_spid: 36, name: "bobsleigh", display_name: nil, active: 0)
Sport.create(leader_spid: 37, name: "freestyle skiing", display_name: nil, active: 0)
Sport.create(leader_spid: 38, name: "luge", display_name: nil, active: 0)
Sport.create(leader_spid: 39, name: "short track speed skating", display_name: nil, active: 0)
Sport.create(leader_spid: 40, name: "skeleton", display_name: nil, active: 0)
Sport.create(leader_spid: 41, name: "snowboard", display_name: nil, active: 0)
Sport.create(leader_spid: 42, name: "speed skating", display_name: nil, active: 0)
Sport.create(leader_spid: 43, name: "figure skating", display_name: nil, active: 0)
Sport.create(leader_spid: 44, name: "miscellaneous", display_name: nil, active: 0)
Sport.create(leader_spid: 45, name: "roller hockey", display_name: nil, active: 0)
Sport.create(leader_spid: 46, name: "beach soccer", display_name: nil, active: 0)
Sport.create(leader_spid: 47, name: "badminton", display_name: nil, active: 0)
Sport.create(leader_spid: 49, name: "archery", display_name: nil, active: 0)
Sport.create(leader_spid: 50, name: "athletics", display_name: nil, active: 0)
Sport.create(leader_spid: 51, name: "beach volleyball", display_name: nil, active: 0)
Sport.create(leader_spid: 55, name: "diving", display_name: nil, active: 0)
Sport.create(leader_spid: 56, name: "equestrian", display_name: nil, active: 0)
Sport.create(leader_spid: 57, name: "fencing", display_name: nil, active: 0)
Sport.create(leader_spid: 58, name: "judo", display_name: nil, active: 0)
Sport.create(leader_spid: 59, name: "modern pentathlon", display_name: nil, active: 0)
Sport.create(leader_spid: 61, name: "canoe", display_name: nil, active: 0)
Sport.create(leader_spid: 62, name: "gymnastics", display_name: nil, active: 0)
Sport.create(leader_spid: 66, name: "rowing", display_name: nil, active: 0)
Sport.create(leader_spid: 67, name: "shooting", display_name: nil, active: 0)
Sport.create(leader_spid: 68, name: "swimming synchronised", display_name: nil, active: 0)
Sport.create(leader_spid: 69, name: "swimming", display_name: nil, active: 0)
Sport.create(leader_spid: 70, name: "taekwondo", display_name: nil, active: 0)
Sport.create(leader_spid: 71, name: "trampoline", display_name: nil, active: 0)
Sport.create(leader_spid: 72, name: "triathlon", display_name: nil, active: 0)
Sport.create(leader_spid: 73, name: "weightlifting", display_name: nil, active: 0)
Sport.create(leader_spid: 74, name: "wrestling", display_name: nil, active: 0)
Sport.create(leader_spid: 75, name: "sailing", display_name: nil, active: 0)
Sport.create(leader_spid: 76, name: "horse racing", display_name: nil, active: 0)
Sport.create(leader_spid: 77, name: "gaelic hurling", display_name: nil, active: 0)
Sport.create(leader_spid: 78, name: "pool", display_name: nil, active: 0)
Sport.create(leader_spid: 79, name: "squash", display_name: nil, active: 0)
Sport.create(leader_spid: 80, name: "chess", display_name: nil, active: 0)
Sport.create(leader_spid: 81, name: "greyhound racing", display_name: nil, active: 0)
Sport.create(leader_spid: 82, name: "harness racing", display_name: nil, active: 0)
Sport.create(leader_spid: 83, name: "e-sports", display_name: nil, active: 0)
Sport.create(leader_spid: 888, name: "test", display_name: "測試", active: 1)
Sport.create(leader_spid: 8888, name: "test", display_name: nil, active: 0)